- init_server.zsh
Added missing dependency to project compliation
> added automatic install

- Makefile
- init_server.zsh
- install_dep.zsh
We don't want to reinstall what is needed every time, so I put it on a seperate makefile command
> split up install and run

- .gitignore
- test/polls/templates/my_template.html
- test/polls/views.py
html page is simple text input with post to send data to API endpoint
index endpoint is simple data fetch and saving to server if method is post, otherwise just html
> added POC of uploading data to the server

- GameServer/wsDjangoCli.py
- GameServer/wsManager.py
- GameServer/wsServer.py
Just swich back with only a ws server.
> allow code to compile

- GameServer/wsDjangoCli.py
- GameServer/wsManager.py
- GameServer/wsServer.py
- Makefile
- htmlpages/game_settings/tournament.html
- pythongameserv/Dockerfile.python
Actually the  ws Server don't run because he can't reach the connection with daphne server.
> Check gamews server with client

- TranServer/user/templates/accountInformation.html
- TranServer/user/templates/dashboard.html
Juste changed a few things to my html pages.
> few updates fis for pages

- Makefile
- TranServer/user/urls.py
- TranServer/user/views.py
> fixed login api

- TranServer/chat/serializers.py
- TranServer/user/serializers.py
- TranServer/user/templates/html/dashboard.html
- TranServer/user/templates/html/login.html
- TranServer/user/templates/html/register.html
- TranServer/user/urls.py
- TranServer/user/views.py
- old/Couettescendence/monapp/urls.py
Added logic to have proper linkage between front end and backend for logging in, out, and signing up
> added signin, log out, log in

- TranServer/chat/templates/html/generalchat.html
- TranServer/user/templates/html/accountInformation.html
- TranServer/user/templates/html/dashboard.html
- TranServer/user/templates/html/header.html
- TranServer/user/templates/html/socialManagement.html
This breaks some of the html logic a bit but allows for greater consistency.
> migrated header to specific header file

- TranServer/tournament/static/tournament.css
- TranServer/tournament/templates/html/tournament.html
making some changes on tournament sliders and prettier frame
> making some changes on tournament sliders and prettier frame

- TranServer/chat/consumer.py
- TranServer/chat/static/generalchat.css
- TranServer/chat/templates/html/generalchat.html
Various small changes to improve chat code quality
> cleaned up chat code a bit

- TranServer/user/static/register.js
- TranServer/user/static/utils.js
- TranServer/user/templates/html/register.html
Moved code to js, getCookie to utils.js
Make sure to include utils.js first before your main js file
> Cleaned up register page

- TranServer/chat/static/generalchat.css
- TranServer/chat/templates/html/generalchat.html
- TranServer/chat/views.py
pop up new chat added still need some pimp and link a Django logic with
> pop up new chat added still need some pimp and link a Django logic with

- TranServer/user/static/register.css
- TranServer/user/static/register.js
- TranServer/user/templates/html/register.html
Now Error message are print in the main frame !
> Now Error message are print in the main frame

- TranServer/chat/models.py
- TranServer/chat/serializers.py
Minor change in preparation for future profile images
> Changed images path

- TranServer/user/views.py
> require login for invite, add lots of checks for upload picture

- TranServer/chat/static/generalchat.js
- TranServer/game/views.py
- TranServer/user/urls.py
- TranServer/user/views.py
/api/friends/ => Get and delete friends
/api/blocked/ => Get, Post, and Delete blocked users
Chat now has propety personal chat. When user is created, a personal chat is created for them. When the chat page loads a personal chat, it is listed as Game Invitations.
> Create personal chat, have APIs for friends and blocked users

- TranServer/game/views.py
Invites game participants to game
> Invite user to chat

- TranServer/user/serializers.py
- TranServer/user/urls.py
- TranServer/user/views.py
Different access for yourself vs other ppl
/api/profile/ => yourself
/api/profile/username/ =>other ppl
> Profile api views added

- TranServer/user/templates/test_password_change.html
- TranServer/user/urls.py
- TranServer/user/views.py
Left a test file under TranServer/user/templates/test_password_change.html
to show to use change password api
> Added change password, change profile values

- TranServer/game/static/home.css
- TranServer/game/templates/html/home.html
- TranServer/tournament/static/tournament.css
- TranServer/tournament/templates/html/tournament.html
- TranServer/user/static/register.css
- TranServer/user/static/socialManagement.css
- TranServer/user/static/socialManagement.js
- TranServer/user/templates/html/socialManagement.html
New frame for invitation received.
> Final_finitions_pages

- TranServer/user/static/socialManagement.css
- TranServer/user/static/socialManagement.js
- TranServer/user/templates/html/socialManagement.html
- TranServer/user/urls.py
- TranServer/user/views.py
Removed users as utility was minimal.
Search bar searches for users, which gets added to respective container.
Two way invites resolve with an automatic friend.
Blocking someone automatically removes invites, friend status, and prevents future invites either way.
> Connect social management to API

- TranServer/user/static/accountInformation.css
- TranServer/user/static/accountInformation.js
- TranServer/user/templates/html/accountInformation.html
Password validation before any changes and add customisation settings game
> Password validation before any changes and add customisation button

- TranServer/user/static/socialManagement.css
- TranServer/user/static/socialManagement.js
> Fix profile picture

- TranServer/user/static/accountInformation.js
- TranServer/user/static/dashboard.css
- TranServer/user/static/dashboard.js
- TranServer/user/templates/html/accountInformation.html
- TranServer/user/templates/html/dashboard.html
- TranServer/user/urls.py
- TranServer/user/views.py
Dashboard now shows picture
can upload profile pic on Account Information's' ('s' needs to be removed)
> Pictures link to API

- TranServer/user/static/utils.js
Should support a wider range of java script and stuff
> fixed issue with elements outside of content container

- TranServer/user/static/accountInformation.css
- TranServer/user/static/accountInformation.js
- TranServer/user/templates/html/accountInformation.html
Just need to be a bit prettier
> Update pass implemented

- TranServer/game/static/js/onlineGame.js
- TranServer/tournament/static/js/tournament.js
- TranServer/tournament/static/tournament.css
- TranServer/tournament/templates/html/tournament.html
NB: Pop up works but need a refresh before.
If you suppress the AddEventListenner in the JabaScript code it will not work properly.
> Pop up works but need a refresh before.

- TranServer/user/static/dashboard.css
- TranServer/user/templates/html/dashboard.html
user connexion round supress
better looking profile pic
better looking buttons
> user connexion round supress

- TranServer/chat/static/generalchat.css
- TranServer/chat/static/generalchat.js
- TranServer/chat/templates/html/generalchat.html
- TranServer/user/templates/html/dashboard.html
button chat frame better looking accout information correction in DashBoard.
> button chat frame better looking

- TranServer/user/static/register.css
- TranServer/user/templates/html/register.html
No more header buttons.
Revision of tne main frame.
> No more header buttons.

- GameServer/game/bottibotto.py
- GameServer/game/gameLogic.py
> bottibotto on steroids

- .gitignore
- GameServer/game/bottibotto.py
- GameServer/game/gameLogic.py
- Makefile
- TranServer/TranServer/settings.py
- TranServer/chat/static/generalchat.js
- TranServer/chat/static/generalchat2.js
- TranServer/chat/templates/html/generalchat.html
- TranServer/chat/views.py
- TranServer/user/static/socialManagement.js
- docker-compose.yml
- nginx/conf/nginx.conf
Started with chat, ended with docker compose
> Turned off debug mode for testing. Crazyness follows.

- TranServer/game/static/js/onlineGame.js
- TranServer/game/static/onlineGame.css
- TranServer/game/templates/html/gameSettings.html
- TranServer/game/templates/html/home.html
rest : start button fixed, user listing are not in the html anymore, but in Javascript
Need to be modify so it can run with the backend.
> home page : game button and not Online Game button

- TranServer/tournament/static/js/tournament.js
- TranServer/tournament/static/tournament.css
- TranServer/tournament/templates/html/tournament.html
And the list container is not static anymore but depending from javascript.
Need to be connected to the server.
> Changed the start button so now it is fixed.

- TranServer/user/static/dashboard.js
- TranServer/user/static/profile_user.js
- TranServer/user/templates/html/profile_user.html
- TranServer/user/views.py
Now viewing /dashboard/<username>/ views other person's profile
> removed image logs, fixed code

- TranServer/user/serializers.py
- TranServer/user/static/accountInformation.js
- TranServer/user/templates/html/accountInformation.html
Setting default colors doesn't seem to work :/
> Added upload colors

- GameServer/wsDjangoCli.py
- TranServer/chat/static/generalchat.js
- TranServer/chat/static/generalchat2.js
- TranServer/game/consumer.py
- TranServer/game/static/js/gameSettings.js
- TranServer/game/static/js/onlineGame.js
- TranServer/game/templates/html/gameSettings.html
- TranServer/game/views.py
- TranServer/tournament/static/js/tournament.js
- TranServer/tournament/templates/html/tournament.html
- TranServer/tournament/views.py
A lot of code. Invitations everywhere. Tournament settings page fixed. Other things I already forgot (commit messages might be helpful)
> Game_tournament_participants

- TranServer/tournament/static/js/tournament.js
- TranServer/tournament/static/tournament.css
- TranServer/tournament/templates/html/tournament.html
- TranServer/tournament/views.py
Correct options javascript
Missing imports
Missing multi option django
> Fix pretty bad bugs

- TranServer/tournament/static/js/tournament.js
Test to see if it still double start.
> slider tournament

- TranServer/chat/static/generalchat2.js
- TranServer/tournament/static/js/tournament.js
> double invite just been resolved for tournament and chat

- GameServer/game/game.py
- GameServer/wsDjangoCli.py
- GameServer/wsServer.py
- TranServer/game/consumer.py
- TranServer/tournament/consumer.py
- TranServer/tournament/views.py
- TranServer/user/views.py
> Fixing bugs

- GameServer/game/game.py
- GameServer/game/gameLogic.py
- TranServer/game/static/js/pong.js
- TranServer/tournament/static/js/bracket.js
if 2 players goes left or right, else can go anywhere
> Game ball spawn
